language: ruby
rvm:
  - 2.2.2
addons:
  code_climate:
    repo_token: dfde3ea1f13524298878000db6943cb43bf37d9f3485b6f15392133157122853
script: bundle exec rspec spec
after_success:
  - bundle exec codeclimate-test-reporter
  